### ISSUE TITLE
Error computing NN outputs

### ISSUE THREAD

**Issue by 2RKowski** [eelretep/mlmodelzoo#1]
Hi, I'm having problems getting the SimpleSample project to work with style transferring.
I've used the "Scream" model (and couple of others) with "Styler" target but it always returns "Error computing NN outputs -1".
What could possibly be an issue here? Thanks!

[mlmodelzoo.mlmodel.zip](https://github.com/eelretep/mlmodelzoo/files/1174258/mlmodelzoo.mlmodel.zip)

**Comment by eelretep** [comment]
Are you using XCode 9 beta 3 and running iOS 11 beta 3?

**Comment by 2RKowski** [comment]
Yeah, that was the issue, I was using older iOS 11 beta. Thanks!
