### ISSUE TITLE
build succeed but VNCoreMLMLTransform request failed

### ISSUE THREAD

**Issue by negi111111** [eelretep/mlmodelzoo#2]
Hi
I downloaded the style transfer model from [mlmodelzoo.com](https://mlmodelzoo.com/product-category/style-transfer/) and tried to build by using [your sample code](https://github.com/eelretep/mlmodelzoo). I succeeded in building it, but I see the following error message.
Since some people asked similar questions in the [Apple Developer Forums](https://forums.developer.apple.com/thread/82852), so is this due to an error in coreml? 

Please help me.

Full errors messages:

> 2017-07-29 06:21:09.633596+0900 SimpleSample[235:5279] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
> 2017-07-29 06:21:09.633966+0900 SimpleSample[235:5279] [MC] Reading from public effective user settings.
> 2017-07-29 06:21:09.673544+0900 SimpleSample[235:5279] Carrier install: 0
> 2017-07-29 06:21:09.673607+0900 SimpleSample[235:5279] Internal install: 0
> 2017-07-29 06:21:15.504173+0900 SimpleSample[235:5426] [core] Error Domain=com.apple.CoreML Code=1 "Input image feature input1 does not match model description" UserInfo={NSLocalizedDescription=Input image feature input1 does not match model description, NSUnderlyingError=0x1c425da30 {Error Domain=com.apple.CoreML Code=1 "Image is not valid width 480, instead is 640" UserInfo={NSLocalizedDescription=Image is not valid width 480, instead is 640}}}
> 2017-07-29 06:21:15.504232+0900 SimpleSample[235:5426] [core] Failure verifying inputs.
> 2017-07-29 06:21:15.504302+0900 SimpleSample[235:5426] Error: The VNCoreMLTransform request failed
> unexpected result type
> Error Domain=com.apple.vis Code=3 "The VNCoreMLTransform request failed" UserInfo={NSLocalizedDescription=The VNCoreMLTransform request failed, NSUnderlyingError=0x1c425da60 {Error Domain=com.apple.CoreML Code=1 "Input image feature input1 does not match model description" UserInfo={NSLocalizedDescription=Input image feature input1 does not match model description, NSUnderlyingError=0x1c425da30 {Error Domain=com.apple.CoreML Code=1 "Image is not valid width 480, instead is 640" UserInfo={NSLocalizedDescription=Image is not valid width 480, instead is 640}}}}}

**Comment by negi111111** [comment]
<img src="https://user-images.githubusercontent.com/23568006/28739063-9e824988-7432-11e7-9160-697c5ba7a131.PNG" width="300" height="600">

**Comment by eelretep** [comment]
Did you choose the style transfer scheme in Xcode? Are you on at least ios 11 beta3?

**Comment by negi111111** [comment]
Oh... I did not choose the style transfer scheme with Xcode beta 4 and ios 11 beta 4. After selecting the scheme and rebuilding it, it worked properly. Thank you👍 

<img src = "https://user-images.githubusercontent.com/23568006/28743694-626ddddc-748b-11e7-901c-bfa2c456d486.png" width = "200" height="400">
